### ISSUE TITLE
NO REQUIREMENTS.TXT

### ISSUE THREAD

**Issue by MatchaSoba** [3nityR/benchmark-parser#3]
I wanna installll mmoddulelssjsss😠😠😠😠😠😠😠😠😠😠😠😠

- [ ] 😠

**Comment by 3nityR** [comment]
**OK**

"OK" (/oʊkeɪ/; spelling variations include "okay", "O.K.", "ok") is an English word denoting approval, acceptance, agreement, assent, or acknowledgment. "OK" is frequently used as a loanword in other languages. It has been described as the most frequently spoken or written word on the planet.

As an adjective, "OK" principally means "adequate" or "acceptable" as a contrast to "bad" ("The boss approved this, so it is OK to send out"); it can also mean "mediocre" when used in contrast with "good" ("The french fries were great, but the burger was just OK"). It fulfills a similar role as an adverb ("Wow, you did OK for your first time skiing!"). As an interjection, it can denote compliance ("OK, I will do that"), or agreement ("OK, that is fine"). It can mean "assent" when it is used as a noun ("the boss gave his OK to the purchase") or, more colloquially, as a verb ("the boss OKed the purchase"). "OK", as an adjective, can express acknowledgment without approval. As a versatile discourse marker or back-channeling item, it can also be used with appropriate voice tone to show doubt or to seek confirmation ("OK?" or "Is that OK?").
